// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvbpkabzcazaflgzddjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2YnBrYWJ6Y2F6YWZsZ3pkZGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxOTY4NzcsImV4cCI6MjEwMjc3Mjg3N30.-Dmx3WhzRH16MwYZpPoUAzkO7FZpvo1gUY8ghwNMbP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});